services:
  mwcp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "100.94.216.28:9001:8080"
    volumes:
      - ./yara_rules:/root/yara_repo
    entrypoint: ["mwcp", "serve", "--host","0.0.0.0","--port","8080"]
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wikijs.rule=HOST(`mwcp.trashcollector.dev`)"
      - "traefik.http.routers.wikijs.entrypoints=https"
      - "traefik.http.routers.wikijs.tls.certresolver=letsencrypt"
