services:
  mwcp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "100.94.216.28:9002:8080"
    entrypoint: ["mwcp", "serve", "--host","0.0.0.0","--port","8080"]
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mwcp.rule=HOST(`mwcp.trashcollector.dev`)"
      - "traefik.http.routers.mwcp.entrypoints=https"
      - "traefik.http.routers.mwcp.tls.certresolver=letsencrypt"
