Archive:
  description: Archive file types
  author: DC3
  parsers:
    - .Zip
    - .Gzip

Decoy:
  description: Generic file types described as a decoy file
  author: DC3
  parsers:
    - .DOC
    - .PDF
    - .RTF
    - .JPG
    - .DOCX
    - .XLSX
    - .PPTX

foo:
  description: example parser that works on any file
  author: DC3
  parsers:
    - .Foo

AutofillFinder:
  description: finds autofill files
  author: fh
  parsers:
    - .GenericVOne

CookieFinder:
  description: A parser to identify potential cookie files in a text format
  author: fh
  parsers:
    - .GenericVOne

CredentialFinder:
  description: A parser to identify potential passwords in a text format
  author: fh
  parsers:
    - .AzVOne
    - .AzVTwo
    - .AzVThree
    - .GenericVTwo
    - .GenericVOne
    - .GenericVThree
HistoryFinder:
  description: A parser to identify browser view history in a text format
  author: fh
  parsers:
    - .GenericVOne

LinuxFinder:
  description: A parser to identify interesting files found on linux
  author: fh
  parsers:
    - .SSHPrivateKey
    - .SSHPublicKey

GenericDropper:
  description: Generic Dropper
  author: DC3
  parsers:
    - .Overlay
    - .RSRC

ISO: .ImageFile

PDF: .Document

PowerShell: .Script

Python:
  description: Python artifacts
  author: DC3
  parsers:
    - .PyInstaller

Quarantined:
  description: Anti-Virus Quarantined File
  author: DC3
  parsers:
    - .McAfee
    - .Defender
    - .SymantecQB
    - .SymantecSubSDK
    - .AhnLab
    - .Avast_AVG

RSA:
  description: RSA artifacts
  author: DC3
  parsers:
    - .DigitalCertificate
    - .PrivateKey

VisualBasic:
  description: VisualBasic Script
  author: DC3
  parsers:
    - .EncodedASP  # must come first
    - .VBE
    - .VBScript
